### ISSUE TITLE
Arquivar e excluir conversas

### ISSUE THREAD

**Issue by yaskisoba** [mdsreq-fga-unb/2023.1-TwoDo#16]
US46 - Eu, como usuário, quero ser capaz de arquivar ou excluir conversas antigas que não são mais relevantes para mim, para manter minha lista de conversas organizada e fácil de usar.

**Comment by fabioaletorres** [comment]
Critério de aceitação: 

- [x] Deve ser possível arquivar um chat privado;
- [x] Deve ser possível acessar um chat privado arquivado;
- [x] Deve ser possível desarquivar um chat privado;
- [x] Deve ser possível retornar a visualização dos chats, a partir da aba das arquivadas.
