### ISSUE TITLE
Pesquisar no histórico

### ISSUE THREAD

**Issue by yaskisoba** [mdsreq-fga-unb/2023.1-TwoDo#17]
US45 - Eu, como usuário, quero ser capaz de pesquisar meu histórico de conversas por palavra-chave ou data específica, para que eu possa encontrar informações importantes de forma rápida e fácil.

**Comment by fabioaletorres** [comment]
Critério de aceitação:

- [x] Deve ter um botão específico que indique a busca no chat.
