### ISSUE TITLE
Conteúdo de avisos analisados por uma IA

### ISSUE THREAD

**Issue by yaskisoba** [mdsreq-fga-unb/2023.1-TwoDo#18]
US48 - Eu, como usuário, gostaria de ter o conteúdo de avisos analisados por uma IA para maior confiabilidade

**Comment by fabioaletorres** [comment]
Critério de aceitação:

- [x] Deve-se retornar a análise da IA solicitada no conteúdo de avisos, quando o conteúdo não estiver em edição.
