### ISSUE TITLE
Conteúdo de mensagens analisado por uma IA

### ISSUE THREAD

**Issue by Arthrok** [mdsreq-fga-unb/2023.1-TwoDo#23]
US51 - Eu, como usuário, gostaria de ter o conteúdo das mensagens no chat analisados por uma IA quando solicitado.

**Comment by fabioaletorres** [comment]
Critério de aceitação:

- [x] O conteúdo deve aparecer a opção de ser analisado pela IA no chat privado;
- [x] Deve-se retornar um resultado da análise do conteúdo no chat privado.
