### ISSUE TITLE
Criação de um chat público

### ISSUE THREAD

**Issue by yaskisoba** [mdsreq-fga-unb/2023.1-TwoDo#8]
**[US37]** Eu, como usuário, quero ser capaz de enviar mensagens públicas para outros usuários em tempo real, para que eu possa ter conversas públicas com outros usuários sem precisar atualizar a página.

**Comment by fabioaletorres** [comment]
Critério de Aceitação:

- [x] Qualquer usuário participante do chat público deve ser capaz de enviar mensagem.

Tasks:

- [x] Criar nova tela para o chat
