### ISSUE TITLE
Criação de um chat privado entre usuários

### ISSUE THREAD

**Issue by yaskisoba** [mdsreq-fga-unb/2023.1-TwoDo#9]
**[US38]** Eu, como usuário, quero ser capaz de enviar mensagens privadas para outros usuários, para que eu possa ter conversas privadas que não são visíveis para outros usuários.

**Comment by fabioaletorres** [comment]
Critérios de Aceitação: 

- [x] Deve ser possível visualizar quando um usuário está digitando; 
- [x] Quaisquer usuários podem enviar mensagens privadas entre dois usuários.
